# Generated by Django 5.2.17 on 2026-09-24 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimediaservicio',
            name='servicio',
        ),
        migrations.CreateModel(
            name='ContenidoMultimediaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO', 'Foto'), ('VIDEO', 'Video')], max_length=10)),
                ('archivo', models.FileField(upload_to='servicios/multimedia/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='catalogo.servicio')),
            ],
            options={
                'verbose_name': 'contenido multimedia',
                'verbose_name_plural': 'contenidos multimedia',
            },
        ),
        migrations.CreateModel(
            name='ElementoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Producto'), ('INSUMO', 'Insumo'), ('EQUIPO', 'Equipo')], max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('especificaciones', models.TextField(blank=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='catalogo.servicio')),
            ],
            options={
                'verbose_name': 'elemento del servicio',
                'verbose_name_plural': 'elementos del servicio',
            },
        ),
        migrations.DeleteModel(
            name='InsumoEquipo',
        ),
        migrations.DeleteModel(
            name='MultimediaServicio',
        ),
    ]
